{{- if .Values.rbac.create -}}
{{/*
Part of Service Binding RBAC feature as per the specification
https://github.com/servicebinding/spec#role-based-access-control-rbac
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "servicebinding-runtime.clusterRoleName" . }}
  labels:
    {{- include "servicebinding-runtime.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      servicebinding.io/controller: "true"
rules: [] # The control plane automatically fills in the rules
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "servicebinding-runtime.clusterRoleName" . }}-workloads
  labels:
    {{- include "servicebinding-runtime.labels" . | nindent 4 }}
    servicebinding.io/controller: "true"
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
# Copied from https://github.com/servicebinding/runtime/blob/main/config/rbac/aggregated_role.yaml
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
# Copied from https://github.com/servicebinding/runtime/blob/main/config/rbac/role.yaml
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebinding.io
  resources:
  - clusterworkloadresourcemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings/finalizers
  verbs:
  - update
- apiGroups:
  - servicebinding.io
  resources:
  - servicebindings/status
  verbs:
  - get
  - patch
  - update
# Copied from https://github.com/servicebinding/runtime/blob/main/config/rbac/auth_proxy_role.yaml
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
# Copied from https://github.com/servicebinding/runtime/blob/main/config/rbac/auth_proxy_client_clusterrole.yaml
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "servicebinding-runtime.clusterRoleBindingName" . }}
  labels:
    {{- include "servicebinding-runtime.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "servicebinding-runtime.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "servicebinding-runtime.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "servicebinding-runtime.fullname" . }}-leader-election
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "servicebinding-runtime.fullname" . }}-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "servicebinding-runtime.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "servicebinding-runtime.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
